pipelines CI-sonar

diff --git a/.github/workflows/CI_informe.yml b/.github/workflows/CI_informe.yml
--- a/.github/workflows/CI_informe.yml
+++ b/.github/workflows/CI_informe.yml
@@ -29,7 +29,7 @@ jobs:
       - name: Build (captura de log)
         id: build
         run: |
-          mvn clean install > build.log 2>&1 || echo "BUILD_FAILED=1" >> $GITHUB_ENV
+          mvn clean verify 2>&1 | tee build.log || echo "BUILD_FAILED=1" >> $GITHUB_ENV
 
       - name: SonarCloud Scan
         run: |
